### ISSUE TITLE
Seems to try and reconnect quite aggressively

### ISSUE THREAD

**Issue by arj03** [staltz/ssb-legacy-conn#2]
Using this in patchbay I have noticed that if a host is down, it just keeps reconnecting over and over again, something like every second:

```
info @6CA SSB- net:pub.scuttlebuttchess.co.uk:8008~shs:GPz52umhSy9c4Qu7jBLd9mDOysvxyy3TcjzUzsaZHVA= ERR
  "connect ECONNREFUSED 68.183.32.46:8008"
info @6CA SSB- net:pub.scuttlebuttchess.co.uk:8008~shs:GPz52umhSy9c4Qu7jBLd9mDOysvxyy3TcjzUzsaZHVA= CONNECTING
info @6CA SSB- net:pub.scuttlebuttchess.co.uk:8008~shs:GPz52umhSy9c4Qu7jBLd9mDOysvxyy3TcjzUzsaZHVA= ERR
  "connect ECONNREFUSED 68.183.32.46:8008"
info @6CA SSB- net:pub.scuttlebuttchess.co.uk:8008~shs:GPz52umhSy9c4Qu7jBLd9mDOysvxyy3TcjzUzsaZHVA= CONNECTING
info @6CA SSB- net:pub.scuttlebuttchess.co.uk:8008~shs:GPz52umhSy9c4Qu7jBLd9mDOysvxyy3TcjzUzsaZHVA= ERR
  "connect ECONNREFUSED 68.183.32.46:8008"
info @6CA SSB- net:pub.scuttlebuttchess.co.uk:8008~shs:GPz52umhSy9c4Qu7jBLd9mDOysvxyy3TcjzUzsaZHVA= CONNECTING
info @6CA SSB- net:pub.scuttlebuttchess.co.uk:8008~shs:GPz52umhSy9c4Qu7jBLd9mDOysvxyy3TcjzUzsaZHVA= ERR
  "connect ECONNREFUSED 68.183.32.46:8008"
info @6CA SSB- net:pub.scuttlebuttchess.co.uk:8008~shs:GPz52umhSy9c4Qu7jBLd9mDOysvxyy3TcjzUzsaZHVA= CONNECTING
info @6CA SSB- net:pub.scuttlebuttchess.co.uk:8008~shs:GPz52umhSy9c4Qu7jBLd9mDOysvxyy3TcjzUzsaZHVA= ERR
  "connect ECONNREFUSED 68.183.32.46:8008"
info @6CA SSB- net:pub.scuttlebuttchess.co.uk:8008~shs:GPz52umhSy9c4Qu7jBLd9mDOysvxyy3TcjzUzsaZHVA= CONNECTING
```

**Comment by arj03** [comment]
Also this is using ssb-friend-pub so it populates the nodes I want to connect to using: sbot.gossip.add. The problem is that it never tries any of the other hosts, it just keeps trying the one that doesn't work. Luckily there is one other that is working, but still ;-)

**Comment by staltz** [comment]
Could you try replacing this with ssb-gossip@1.0.10 and checking whether the issue still occurs? Basically the only concern I have with ssb-legacy-conn is to mirror ssb-gossip behavior, even the bugs, if it comes to that.

Also there have been some updates to ssb-gossip, I reflected those in ssb-legacy-conn and released 1.0.25 yesterday. Did Patchbay update?

**Comment by arj03** [comment]
I tested with 1.0.25. I'll try gossip later today. Thanks for your quick input :)

**Comment by arj03** [comment]
I tested ssb-gossip and it has the same behaviour, so yeah not a bug in that sense :)

I bumped the dep in patchbay just now btw.

Thanks
