### ISSUE TITLE
2.0.0 backward-incompatibilty

### ISSUE THREAD

**Issue by christianbundy** [staltz/ssb-legacy-conn#3]
Hey @staltz! I saw that you recently released 2.0.0, but after looking at the commits I'm not sure which bits are backward-incompatible. Anything I should be aware of? Thanks!

**Comment by staltz** [comment]
Hey @christianbundy, it's because you gotta compare way back, with ssb-legacy-conn 1.0.25. The difference is that 2.0.0 uses ssb-conn which demands Node.js 6.5 or higher, and secret-stack@^6.2.0.

**Comment by christianbundy** [comment]
Oh, cool, thank you! I'll upgrade now.
